FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR ./
COPY ./AppApi/AppApi.csproj ./
RUN dotnet restore
COPY . ./
RUN dotnet build
RUN dotnet publish -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR ./
COPY --from=build /out ./
ENTRYPOINT ["dotnet", "AppApi.dll"]
